export const TESTNET_URL = 'https://api.testnet.minepi.com';
export const MAINNET_URL = 'https://api.mainnet.minepi.com';
export const PUBLIC_KEY =
  'GDPG2HQKWMSKOM7SOAEXNOUVZOKBOOQX2ALDFXRXPHUUHUR3SEQN2PEY';
export const SECRET_KEY =
  'SCF4S3GJ623TYPWRHCFWD3ARXEDMPGDB3BRGRT3CIK4GFRZS6YWDVEN3';
